#!/bin/bash
# ============================================================================
# Clawkeeper Remediation: NanoClaw Mount Allowlist
# Fixes permissions and creates secure mount-allowlist.json if needed.
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/helpers.sh
source "${SCRIPT_DIR}/../../lib/helpers.sh" 2>/dev/null || true

remediation_id="${1:-}"
config_dir="$HOME/.config/nanoclaw"
allowlist_file="$config_dir/mount-allowlist.json"

case "$remediation_id" in
    fix_nanoclaw_config_dir_perms)
        if chmod 700 "$config_dir" 2>/dev/null; then
            emit_pass "Fixed config directory permissions to 700" "Config Permissions"
        else
            emit_fail "Could not fix config directory permissions" "Config Permissions"
        fi
        ;;
    fix_nanoclaw_allowlist_perms)
        if chmod 600 "$allowlist_file" 2>/dev/null; then
            emit_pass "Fixed allowlist file permissions to 600" "Allowlist Permissions"
        else
            emit_fail "Could not fix allowlist permissions" "Allowlist Permissions"
        fi
        ;;
    create_allowlist)
        mkdir -p "$config_dir"
        chmod 700 "$config_dir"
        
        cat > "$allowlist_file" << 'ALLOWLIST_EOF'
{
  "version": 1,
  "description": "NanoClaw mount allowlist - generated by Clawkeeper",
  "nonMainReadOnly": true,
  "blocklist": [
    ".ssh",
    ".gnupg",
    ".aws",
    ".azure",
    ".gcloud",
    ".kube",
    ".docker",
    ".env",
    ".netrc",
    ".npmrc",
    "credentials",
    "private_key",
    "id_rsa",
    "id_ed25519",
    ".secret",
    ".password",
    "secrets.json",
    "config.json"
  ],
  "allowlist": []
}
ALLOWLIST_EOF

        chmod 600 "$allowlist_file"
        emit_pass "Created secure mount-allowlist.json" "Mount Allowlist"
        ;;
    *)
        emit_fail "Unknown remediation: $remediation_id" "Remediation"
        ;;
esac
