#!/bin/bash
# ============================================================================
# Clawkeeper Bundle Script
# Concatenates lib/ + checks/ into a single dist/clawkeeper.sh file.
#
# Usage: bash scripts/bundle.sh
# Output: dist/clawkeeper.sh
#
# Concatenation order:
#   1. helpers.sh    — JSON output helpers
#   2. ui.sh         — colors, formatting, output helpers
#   3. scanner.sh    — check runner, detection, reporting
#   4. agent.sh      — SaaS agent management
#   5. deploy.sh     — OpenClaw deployment (native + Docker)
#   6. uninstall.sh  — secure removal
#   7. checks/       — extracted security checks
#   8. orchestrator.sh — CLI entrypoint (main, usage, platform detect)
# ============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$REPO_ROOT/dist"
OUTPUT="$DIST_DIR/clawkeeper.sh"
CHECKS_DIR="$REPO_ROOT/checks"
LIB_DIR="$REPO_ROOT/lib"

mkdir -p "$DIST_DIR"

echo "Bundling clawkeeper.sh..."

{
    # --- Shebang + header ---
    cat <<'HEADER'
#!/bin/bash
# ============================================================================
# CLAW Keeper Setup Wizard
# Harden your host. Deploy OpenClaw securely.
#
# By RAD Security — https://rad.security
#
# This file is auto-generated by scripts/bundle.sh — do not edit directly.
# ============================================================================

set -uo pipefail
HEADER

    echo ""
    echo "# === Shared Helpers ======================================================"
    echo ""

    # --- Inline lib/helpers.sh (strip shebang) ---
    sed '1{/^#!/d;}' "$LIB_DIR/helpers.sh"

    echo ""
    echo "# === UI (colors, formatting, output) ====================================="
    echo ""

    cat "$LIB_DIR/ui.sh"

    echo ""
    echo "# === Scanner (check runner, detection, reporting) ========================"
    echo ""

    cat "$LIB_DIR/scanner.sh"

    echo ""
    echo "# === Agent (SaaS integration) ============================================"
    echo ""

    cat "$LIB_DIR/agent.sh"

    echo ""
    echo "# === Deploy (OpenClaw installation) ======================================"
    echo ""

    cat "$LIB_DIR/deploy.sh"

    echo ""
    echo "# === Uninstall (secure removal) =========================================="
    echo ""

    cat "$LIB_DIR/uninstall.sh"

    echo ""
    echo "# === Extracted Checks ===================================================="
    echo ""

    # --- Inline each check from checks/<id>/ ---
    for check_dir in "$CHECKS_DIR"/*/; do
        [ -d "$check_dir" ] || continue
        local_id=$(basename "$check_dir")
        toml_file="$check_dir/check.toml"
        check_file="$check_dir/check.sh"
        remediate_file="$check_dir/remediate.sh"

        if [ ! -f "$check_file" ]; then
            echo "WARNING: No check.sh in $check_dir — skipping" >&2
            continue
        fi

        # Read metadata from TOML (simple key=value parser)
        local_name="$local_id"
        if [ -f "$toml_file" ]; then
            local_name=$(grep '^name *=' "$toml_file" | sed 's/^name *= *"\(.*\)"/\1/' | head -1)
            [ -z "$local_name" ] && local_name="$local_id"
        fi

        echo "# --- Check: $local_id ---"
        echo ""

        # Metadata accessor function
        cat <<METAFUNC
__meta_${local_id}() {
    case "\$1" in
        name) echo "$local_name" ;;
        id)   echo "$local_id" ;;
    esac
}
METAFUNC

        echo ""

        # Wrap check.sh as __check_<id>() function
        # Strip shebang, SCRIPT_DIR, source lines, shellcheck directives, and 'exit' → 'return'
        echo "__check_${local_id}() {"
        sed \
            -e '1{/^#!/d;}' \
            -e '/^SCRIPT_DIR=/d' \
            -e '/^# shellcheck source=/d' \
            -e '/^source.*helpers\.sh/d' \
            -e 's/^[[:space:]]*exit 0$/return 0/' \
            -e 's/^[[:space:]]*exit 1$/return 1/' \
            -e 's/^[[:space:]]*exit$/return/' \
            "$check_file"
        echo "}"
        echo ""

        # Wrap remediate.sh as __remediate_<id>() function (if exists)
        if [ -f "$remediate_file" ]; then
            echo "__remediate_${local_id}() {"
            sed \
                -e '1{/^#!/d;}' \
                -e '/^SCRIPT_DIR=/d' \
                -e '/^# shellcheck source=/d' \
                -e '/^source.*helpers\.sh/d' \
                -e 's/^[[:space:]]*exit 0$/return 0/' \
                -e 's/^[[:space:]]*exit 1$/return 1/' \
                -e 's/^[[:space:]]*exit$/return/' \
                "$remediate_file"
            echo "}"
            echo ""
        fi
    done

    echo "# === Orchestrator (entrypoint) ==========================================="
    echo ""

    # --- Inline lib/orchestrator.sh (entrypoint — must be last) ---
    cat "$LIB_DIR/orchestrator.sh"

} > "$OUTPUT"

chmod +x "$OUTPUT"

# Count stats
check_count=$(find "$CHECKS_DIR" -name "check.sh" 2>/dev/null | wc -l | tr -d ' ')
lib_count=$(find "$LIB_DIR" -name "*.sh" 2>/dev/null | wc -l | tr -d ' ')
line_count=$(wc -l < "$OUTPUT" | tr -d ' ')
echo "Done: $OUTPUT ($line_count lines, $lib_count lib modules, $check_count extracted checks)"
